config/routes.rb
ActionController::Routing::Routes.draw do |map|

  

  map.admin_root "/admin", :controller => "admin/home"
  map.admin_login "/admin/login", :controller => "admin/home", :action => "login"
  map.admin_logout "/admin/logout", :controller => "admin/home", :action => "logout"

  map.namespace :admin do |admin|
    admin.resources :pages, :collection => { :sort => :put }
    admin.resources :home_pages, :controller => "pages"
    admin.resources :static_pages, :controller => "pages"
    admin.resources :contact_pages, :controller => "pages"
    admin.resources :portfolios, :controller => "pages"
    admin.resources :works, :member => {:update_pictures => :post}
    admin.resources :posts
    admin.resources :products, :member => {:clone => :get, :update_pictures => :post}
    admin.resources :categories
    admin.resources :product_categories, :controller => "categories"
    admin.resources :work_categories, :controller => "categories"
    admin.resources :feature_categories, :controller => "categories"
    admin.resources :pictures#, :only => [:create, :delete]
    admin.resources :features, :collection => {:for_category => :post}
    admin.resources :text_features, :controller => 'features'
    admin.resources :color_features, :controller => 'features'
    admin.resources :options, :collection => {:for_feature => :post}
    admin.resources :product_options
    admin.resources :option_combinations, :collection => {:add_option => :post}
    admin.resources :offers
  end
    
  map.work '/galeria/:id', :controller => 'works', :action => 'show', :requirements => {:id => /\d+/}
  map.works '/galeria', :controller => 'works', :action => 'index'
  map.works_category '/galeria/:category_id', :controller => 'works', :action => 'index'
  map.product '/produkty/:id', :controller => 'products', :action => 'show', :requirements => {:id => /\d+/}
  map.products '/produkty', :controller => 'products', :action => 'index'
  map.resources :products, :only => [], :collection => {:change_view => :get, :change_order => :get}
  map.products_category '/produkty/:category_id', :controller => 'products', :action => 'index'
  map.resources :offers, :as => "promocje"
  map.resources :posts
  map.resources :categories
  map.page '/:id', :controller => "pages", :action => "show", :conditions => {:parent_id => nil}

  map.root :controller => "pages", :action => "show"

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/work.rb
class Work < ActiveRecord::Base

  has_many :pictures, :as => :assetable, :dependent => :destroy, :order => :item_order
  has_many :category_items, :as => :item, :dependent => :destroy
  has_many :categories, :through => :category_items

  named_scope :active, :conditions => {:status => true}

  named_scope :for_categories, lambda {|categories| {:conditions => ["categories.id in (?)", categories.map(&:id)], :include => :categories}}
  
  cattr_reader :per_page
  @@per_page = 10
  
  def image
      pictures.first
  end

  def self.newest limit=1
      active.find(:all, :limit => limit, :order => "created_at desc")
  end
end

app/controllers/admin/works_controller.rb
class Admin::WorksController < ApplicationController
  layout "admin"
  # GET /works
  # GET /works.xml
  def index
    @works = Work.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @works }
    end
  end

  # GET /works/1
  # GET /works/1.xml
  def show
    @work = Work.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @work }
    end
  end

  # GET /works/new
  # GET /works/new.xml
  def new
    @work = Work.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @work }
    end
  end

  # GET /works/1/edit
  def edit
    @work = Work.find(params[:id])
  end

  # POST /works
  # POST /works.xml
  def create
    @work = Work.new(params[:work])

    respond_to do |format|
      if @work.save
        flash[:notice] = 'Work was successfully created.'
        format.html { redirect_to(admin_works_url) }
        format.xml  { render :xml => @work, :status => :created, :location => @work }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @work.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /works/1
  # PUT /works/1.xml
  def update
    @work = Work.find(params[:id])

    respond_to do |format|
      if @work.update_attributes(params[:work])
        flash[:notice] = 'Work was successfully updated.'
        format.html { redirect_to(admin_works_url) }
        format.js { render :text => '', :status => :ok }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.js { render :text => '', :status => :unprocessable_entity }
        format.xml  { render :xml => @work.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update_pictures
    success = false
    @work = Work.find_by_id(params[:id])
    begin
      @work.pictures.each{|picture| picture.data.reprocess!}    
      success = true
    rescue
    end
    respond_to do |format|
      if success
        format.js { render :text => '', :status => :ok }
      else
        format.js { render :text => '', :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.xml
  def destroy
    @work = Work.find(params[:id])
    @work.destroy

    respond_to do |format|
      format.html { redirect_to(admin_works_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    if params[:category_id]      	  
      @category = WorkCategory.find_by_permalink(params[:category_id])
      @works = @category ? Work.for_categories(@category.all_children).paginate(:page => params[:page]) : []
	  else
      @works = Work.paginate(:page => params[:page], :order => "created_at desc")
	  end
  end
  
  def show
    @work = Work.find_by_id(params[:id])	  	  
	  render :text => "Nie znaleziono realizacji." unless @work
  end   
end

app/helpers/admin/works_helper.rb
module Admin::WorksHelper
end

app/views/admin/works/_form.html.erb
<% form_for([:admin,  @work]) do |f| %>
  <%= f.error_messages %>
  
  <fieldset> <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
    
    <p>
      <label>Tytuł</label>
      <%= f.text_field :name, :class => "text-input small-input" %>
    </p>

    <p>
      <label>Zawartość</label>
      <%= f.cktext_area :description, :toolbar=>'Full', :width=>'99%', :language => 'pl' %>
    </p>

    <p>
      <%= f.label 'work[category_ids][]', "Kategoria" %><br />
      <%= collection_select :work, :category_ids, WorkCategory.find(:all, :order => 'name ASC'), :id, :name, { :selected => @work.category_ids }, { :multiple => false, :name => 'work[category_ids][]' } -%>
    </p>
        
    <p>
      <label>Status</label>
      <%= f.check_box :status %> Aktywna?
    </p>
                
    <p>
      <input class="button" type="submit" value="Zapisz" />
    </p>
    
  </fieldset>
  
  <div class="clear"></div><!-- End .clear -->
<% end %>

app/views/admin/works/edit.html.erb
<div class="content-box">  
  <div class="content-box-header">    
    <h3>Edycja realizacji</h3>

    <ul class="content-box-tabs">
      <li><a href="#tab1" class="default-tab">Opis</a></li> <!-- href must be unique and match the id of target div -->
      <li><a href="#tab2">Zdjecia</a></li>
    </ul>
    
    <div class="clear"></div>
  </div>  
  <div class="content-box-content">
    <div class="tab-content default-tab" id="tab1"> <!-- This is the target div. id must match the href of this div's tab -->
      <%= render :partial => "form" %>
      
      <%= link_to 'Wróć', admin_works_path %>
    </div>
    <div class="tab-content" id="tab2">      
      <% remote_form_for [:admin, @work], :success => "alert('Konfiguracja znakow wodnych aktywna dla nowo uploadowanych zdjec.');", :failure => "alert('Wystapil problem')" do |f| %>
        Znaki wodne: <br />
        Romiq: <%= f.check_box :watermark %><br />
        Archon: <%= f.check_box :watermark_2 %><br />
        <%= f.submit 'Zapisz' %>
      <% end %>
      <%= link_to_remote 'Zastosuj aktualna konfiguracje znakow wodnych do wszystkich zuploadowanych zdjec', :url => update_pictures_admin_work_path(@work), :success => "alert('Zdjecia zaktualizowane')", :failure => "alert('Wystapil problem.')", :loading => "$('#pictures_update_spinner').toggle();", :complete => "$('#pictures_update_spinner').toggle();" %>
      <%= image_tag 'spinner.gif', :style => "display:none;", :id => "pictures_update_spinner" %>
      <ul id="pictures_list">
        <%= render :partial => 'shared/picture', :collection => @work.pictures %>
      </ul>
      <div class="clear"></div>

      <%= swfupload_head %>

      <%= swfupload :controller => '/admin/pictures', :action => 'create', :assetable_id => @work.id, :assetable_type => @work.class.to_s %>

   </div>
  </div>  
</div>

<%= sortable_element("pictures_list", :url => { :controller => 'admin/pictures', :action => "order" }, :constraint => false) %>

app/views/admin/works/index.html.erb
<div class="content-box"><!-- Start Content Box -->
  
  <div class="content-box-header">
    
    <h3>Zarządzaj galeriami</h3>

    <ul class="content-box-tabs">
      <li><a href="#tab1" class="default-tab">Galerie</a></li> <!-- href must be unique and match the id of target div -->
      <li><a href="#tab2">Kategorie</a></li>
    </ul>
        
    <div class="clear"></div>
    
  </div> <!-- End .content-box-header -->
  
  <div class="content-box-content">
    
    <div class="tab-content default-tab" id="tab1"> <!-- This is the target div. id must match the href of this div's tab -->
            
      <table>
	
	<thead>
	  <tr>
	    <th>Tytuł</th>
	    <th>Zawartość</th>
	    <th>Status</th>
	    <th style="width:70px;">&nbsp;</th>
	  </tr>
	  
	</thead>
	
	<tfoot>
	  <tr>
	    <td colspan="6">
	      <div class="bulk-actions align-left">
		<%= link_to 'Dodaj realizację', new_admin_work_path %>
	      </div>
	      
	      <div class="pagination" style="display:none;">
		<a href="#" title="First Page">&laquo; First</a><a href="#" title="Previous Page">&laquo; Previous</a>
		<a href="#" class="number" title="1">1</a>
		<a href="#" class="number" title="2">2</a>
		<a href="#" class="number current" title="3">3</a>
		<a href="#" class="number" title="4">4</a>
		<a href="#" title="Next Page">Next &raquo;</a><a href="#" title="Last Page">Last &raquo;</a>
	      </div> <!-- End .pagination -->
	      <div class="clear"></div>
	    </td>
	  </tr>
	</tfoot>
	
	<tbody>

	  <% @works.each do |work| %>
	  <tr class="parent">
	    <td class="name"><%= link_to work.name, edit_admin_work_path(work) %></td>
	    <td><%= truncate(strip_tags(work.description), :length => 100) %></td>
	    <td><%=h work.status.to_s(:activation) %></td>
	    <td>
	      <%= link_to '<img src="/images/icons/pencil.png" alt="Edytuj" />', edit_admin_work_path(work) %>
	      <%= link_to '<img src="/images/icons/cross.png" alt="Usuń" />', [:admin, work], :confirm => 'Jesteś pewien?', :method => :delete %>
	    </td>
	  </tr>
	  <% work.pictures do |picture| %>
	     <tr><td><%= image_tag picture.url_thumb %></td></tr>
	  <% end %>
	  <% end %>
	</tbody>
	
      </table>
      
    </div> <!-- End #tab1 -->

    <div class="tab-content" id="tab2"> <!-- This is the target div. id must match the href of this div's tab -->
      <h3>Kategorie</h3>
      <%= category_list WorkCategory, true %>
    </div>
        
  </div> <!-- End .content-box-content -->
  
</div> <!-- End .content-box -->

app/views/admin/works/new.html.erb
<div class="content-box">  
  <div class="content-box-header">
    <h3>Nowa realizacja</h3>
  </div>
  <div class="content-box-content">
    <%= render :partial => "form" %>
    
    <%= link_to 'Wróć', admin_works_path %>
  </div>  
</div>

app/views/admin/works/show.html.erb
<%= link_to 'Edit', edit_admin_work_path(@work) %> |
<%= link_to 'Back', admin_works_path %>