config/routes.rb
ActionController::Routing::Routes.draw do |map|

  

  map.admin_root "/admin", :controller => "admin/home"
  map.admin_login "/admin/login", :controller => "admin/home", :action => "login"
  map.admin_logout "/admin/logout", :controller => "admin/home", :action => "logout"

  map.namespace :admin do |admin|
    admin.resources :pages, :collection => { :sort => :put }
    admin.resources :home_pages, :controller => "pages"
    admin.resources :static_pages, :controller => "pages"
    admin.resources :contact_pages, :controller => "pages"
    admin.resources :portfolios, :controller => "pages"
    admin.resources :works, :member => {:update_pictures => :post}
    admin.resources :posts
    admin.resources :products, :member => {:clone => :get, :update_pictures => :post}
    admin.resources :categories
    admin.resources :product_categories, :controller => "categories"
    admin.resources :work_categories, :controller => "categories"
    admin.resources :feature_categories, :controller => "categories"
    admin.resources :pictures#, :only => [:create, :delete]
    admin.resources :features, :collection => {:for_category => :post}
    admin.resources :text_features, :controller => 'features'
    admin.resources :color_features, :controller => 'features'
    admin.resources :options, :collection => {:for_feature => :post}
    admin.resources :product_options
    admin.resources :option_combinations, :collection => {:add_option => :post}
    admin.resources :offers
  end
    
  map.work '/galeria/:id', :controller => 'works', :action => 'show', :requirements => {:id => /\d+/}
  map.works '/galeria', :controller => 'works', :action => 'index'
  map.works_category '/galeria/:category_id', :controller => 'works', :action => 'index'
  map.product '/produkty/:id', :controller => 'products', :action => 'show', :requirements => {:id => /\d+/}
  map.products '/produkty', :controller => 'products', :action => 'index'
  map.resources :products, :only => [], :collection => {:change_view => :get, :change_order => :get}
  map.products_category '/produkty/:category_id', :controller => 'products', :action => 'index'
  map.resources :offers, :as => "promocje"
  map.resources :posts
  map.resources :categories
  map.page '/:id', :controller => "pages", :action => "show", :conditions => {:parent_id => nil}

  map.root :controller => "pages", :action => "show"

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/feature.rb
class Feature < ActiveRecord::Base
  has_many :options
  has_many :category_items, :as => :item, :dependent => :destroy
  has_many :categories, :through => :category_items

  validates_uniqueness_of :name, :message => 'Istnieje juz cecha o takiej nazwie.'
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  has_many :offer_items
  has_many :products, :through => :offer_items, :source => :item, :source_type => "Product"
  has_many :categories, :through => :offer_items, :source => :item, :source_type => "Category"

  named_scope :active, :conditions => {:status => true}
  
  def all_products
    all_products = products.active
    all_products += categories.map{|c| c.products.active}.flatten
    all_products
  end
end

app/controllers/admin/offers_controller.rb
# -*- coding: utf-8 -*-
class Admin::OffersController < ApplicationController

  layout "admin"

  def index
    @offers = Offer.all(:order => "created_at desc")
  end

  def show
    @offer = Offer.find_by_id(params[:id])
  end

  def new
    @offer = Offer.new
  end

  def edit
    @offer = Offer.find_by_id(params[:id])
  end

  def create
    @offer = Offer.new(params[:offer])
    
    respond_to do |format|
      if @offer.save
        flash[:notice] = 'Promocja zostałs zapisana.'
        format.html { redirect_to(admin_offers_path) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @offer = Offer.find_by_id(params[:id])
    params[:offer] ||= {}
    params[:offer][:product_ids] ||= []
    params[:offer][:category_ids] ||= []
    respond_to do |format|
      if @offer.update_attributes(params[:offer])
        flash[:notice] = 'Promocja zostałs zaktualizowana.'
        format.html { redirect_to(admin_offers_path) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @offer = Offer.find_by_id(params[:id])
    @offer.destroy

    respond_to do |format|
      format.html { redirect_to(admin_offers_path) }
    end
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    #if params[:category_id]      	  
    #  @category = OfferCategory.find_by_permalink(params[:category_id])
    #  @offers = @category ? @category.all_children.map{|c| c.offers}.flatten : []
	  #else
      @offers = Offer.all(:order => "created_at desc")
	  #end
  end
  
  def show
    @offer = Offer.find_by_id(params[:id])
	  render :text => "Nie znaleziono promocji." unless @offer
  end   
end

app/views/offers/_photos.html.erb
<% photos ||= @product.pictures %>
<div class="grid_9"style="margin:0 0 20px 0;padding:0;border-bottom:1px solid #ddd;">
  <div class="grid_5" style="margin-left:0;">
    <% if photos.present? %>
      <%= image_tag(photos.first.url(:content), :class => "shadow-large", :style => "margin-bottom:20px;", :id => 'main_image') %>
    <% else %>
      <p>Brak zdjec produktu spelniajacego podane kryteria.</p>
    <% end %>
  </div>
  
  <div class="grid_3">
    <% form_remote_tag :url => {:controller => 'products', :action => 'pictures_for_options', :product_id => @product.id}, :update => "product_photos" do |f| %>
      <ul style="list-style:none;">
        <% option_combinations = @product.option_combinations %> 
        <% option_combinations.map{|oc| oc.features}.flatten.uniq.each do |feature| %>
          <li>
            <span><%= feature.name %></span><br />
            <% option_ids = params[:options].to_a.reject{|o| o.blank?}.map{|o| o.to_i} %>
            <% options = option_combinations.map{|oc| oc.options.for_feature(feature)}.flatten.uniq %>
            <% if feature.is_a? ColorFeature %> 
              <span class="color_option_wrapper">
                <label for="color_0"><span class="color_option_label" style="height:36px;width:36px;border:1px solid #999;">Bez znaczenia</span></label>
                <%= radio_button_tag "options[]", "", !option_ids.any?{|oid| options.map(&:id).include?(oid)}, {:id => "color_0", :onclick => "this.form.submit.click();"} %>
              </span>
              <% options.each do |option| %>
                <span class="color_option_wrapper">
                  <label for="<%= "color_#{option.id}" %>">
                    <% if option.texture.present? %>
                      <span style="display:block;"><%= image_tag option.texture.url(:thumb) %></span>
                    <% elsif option.color_code.present? %>
                      <span class="color_option_label" style="background:#<%= option.color_code %>;">&nbsp;</span>
                    <% else %>
                      <span class="color_option_label" style="height:36px;width:36px;border:1px solid #999;"><%= option.name %></span>
                    <% end %>
                  </label>
                  <%= radio_button_tag "options[]", option.id, option_ids.include?(option.id), {:id => "color_#{option.id}", :onclick => "this.form.submit.click();"} %>
                </span>
              <% end %>
              <span class="clear"></span>              
            <% else %>
              <%= select_tag "options[]", options_for_select([["Bez znaczenia",nil]]+options.map{|o| [o.name, o.id]}, (option_ids & options.map{|o| o.id})), :onchange => "this.form.submit.click();" %>
            <% end %>
          </li>
        <% end %>
      </ul>
      <%= submit_tag 'Odswiez', :name => 'submit', :style => "display:none;" %>
    <% end %>
  </div>
</div>
<div>
  <% photos.each do |picture| %>
    <%= image_tag(picture.url(:thumb), :class => "shadow-large", :alt => "", :style => "margin-right:10px;cursor:pointer;", :title => picture.url(:content), :onclick => "$('#main_image').hide();$('#main_image')[0].src = this.title;$('#main_image').fadeIn()") %>
  <% end %>
</div>
<hr />

app/views/offers/index.html.erb
<div class="grid_3 nested_lists">
  <h3>Aktualne promocje</h3>
  <% Offer.active.each do |offer| %>
    <%= link_to offer.name, offer_path(offer) %>
  <% end %>
</div>
<div class="grid_9" style="margin:0;">
  <% for offer in @offers do %>
    <h3><%= offer.name %></h3>
    <div class="grid_5" style="margin-left:0;">
      <% # image_tag(offer.image.url(:content), :class => "shadow-large") if offer.image %>
    </div>
    <div class="grid_4" style="margin:0;height:180px;overflow:hidden;text-align:justify;">
      <%= strip_tags(offer.description) %>
    </div>
    <%= link_to 'wiecej...', offer_path(offer), :class => "more right" %>
    <div class="clear"></div>
    <hr />
  <% end %>
</div>

app/views/offers/show.html.erb
<div class="grid_3 nested_lists" style="text-align:justify;">
  <h3>Aktualne promocje</h3>
  <% Offer.active.each do |offer| %>
    <%= link_to offer.name, offer_path(offer) %>
  <% end %>
</div>
<div class="grid_9" style="margin:0;">
  <h2><%= @offer.name %></h2>  
  <%= @offer.description %>
  <h5>Produkty w promocji</h5>
  <% @offer.all_products.each do |product| %>
    <div style="float:left;width:100px;margin:5px;">
      <%= link_to(image_tag(product.image.url(:thumb)), product_path(product)) if product.image %><br />
      <%= link_to product.name, product_path(product) %>
    </div>
  <% end %>
</div>