config/routes.rb
ActionController::Routing::Routes.draw do |map|

  

  map.admin_root "/admin", :controller => "admin/home"
  map.admin_login "/admin/login", :controller => "admin/home", :action => "login"
  map.admin_logout "/admin/logout", :controller => "admin/home", :action => "logout"

  map.namespace :admin do |admin|
    admin.resources :pages, :collection => { :sort => :put }
    admin.resources :home_pages, :controller => "pages"
    admin.resources :static_pages, :controller => "pages"
    admin.resources :contact_pages, :controller => "pages"
    admin.resources :portfolios, :controller => "pages"
    admin.resources :works, :member => {:update_pictures => :post}
    admin.resources :posts
    admin.resources :products, :member => {:clone => :get, :update_pictures => :post}
    admin.resources :categories
    admin.resources :product_categories, :controller => "categories"
    admin.resources :work_categories, :controller => "categories"
    admin.resources :feature_categories, :controller => "categories"
    admin.resources :pictures#, :only => [:create, :delete]
    admin.resources :features, :collection => {:for_category => :post}
    admin.resources :text_features, :controller => 'features'
    admin.resources :color_features, :controller => 'features'
    admin.resources :options, :collection => {:for_feature => :post}
    admin.resources :product_options
    admin.resources :option_combinations, :collection => {:add_option => :post}
    admin.resources :offers
  end
    
  map.work '/galeria/:id', :controller => 'works', :action => 'show', :requirements => {:id => /\d+/}
  map.works '/galeria', :controller => 'works', :action => 'index'
  map.works_category '/galeria/:category_id', :controller => 'works', :action => 'index'
  map.product '/produkty/:id', :controller => 'products', :action => 'show', :requirements => {:id => /\d+/}
  map.products '/produkty', :controller => 'products', :action => 'index'
  map.resources :products, :only => [], :collection => {:change_view => :get, :change_order => :get}
  map.products_category '/produkty/:category_id', :controller => 'products', :action => 'index'
  map.resources :offers, :as => "promocje"
  map.resources :posts
  map.resources :categories
  map.page '/:id', :controller => "pages", :action => "show", :conditions => {:parent_id => nil}

  map.root :controller => "pages", :action => "show"

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/feature.rb
class Feature < ActiveRecord::Base
  has_many :options
  has_many :category_items, :as => :item, :dependent => :destroy
  has_many :categories, :through => :category_items

  validates_uniqueness_of :name, :message => 'Istnieje juz cecha o takiej nazwie.'
end

app/models/product.rb
class Product < ActiveRecord::Base
#  has_attached_file :image, :styles => {:thumb => "80>",
#  		    	    	       	:medium => "300>"},
#  :path => ":rails_root/public/assets/:attachment/:class/:id/:style/:filename", 
#  :url => "/assets/:attachment/:class/:id/:style/:filename", :default_url => "/images/missing.png"

  has_permalink :name, :unique => true, :to_param => :permalink

  has_many :pictures, :as => :assetable, :dependent => :destroy, :order => :item_order
  has_many :category_items, :as => :item, :dependent => :destroy
  has_many :categories, :through => :category_items

  has_many :option_combinations, :dependent => :destroy

  named_scope :active, :conditions => {:status => true}

  named_scope :for_categories, lambda {|categories| {:conditions => ["categories.id in (?)", categories.map(&:id)], :include => :categories}}

#  cattr_reader :per_page
#  @@per_page = 10

  ALLOWED_VIEWS = {'short_view' => 50, 'medium_view' => 32, 'long_view' => 10}

  ALLOWED_ORDERS = {'date' => 'products.created_at desc', 'name' => 'products.name'}

  def self.newest limit=1
    active.find(:all, :limit => limit, :order => "created_at desc")
  end
  
  def image
    pictures.first
  end
end

app/controllers/admin/products_controller.rb
# -*- coding: utf-8 -*-
class Admin::ProductsController < ApplicationController

  layout "admin"

  def index
    @products = Product.all(:order => "created_at desc")
    @features = Feature.all
  end

  def show
    @product = Product.find_by_id(params[:id])
  end

  def new
    @product = Product.new
  end

  def clone
    origin = Product.find_by_id(params[:id])
    @product = origin.clone
    @product.name = origin.name + ' kopia'
#     combinations = []
#     origin.option_combinations.each do |orig_comb|
#       pictures = []
#       new_comb = orig_comb.clone
#       new_comb.product_id = @product.id
#       orig_comb.option_combination_pictures.each do |orig_pict|
#         new_pict = orig_pict.clone
#         new_pict.option_combination_id = new_comb.id
#         pictures << new_pict
#       end
#       new_comb.option_combination_pictures = pictures
#       combinations << new_comb
#     end
#     @product.option_combinations = combinations
#    categories = origin.category_items.map{|c| c.clone}
#    categories.each{|c| c.item_id = @product.id}
    @product.categories = origin.categories.clone
    render :action => 'new'
  end

  def edit
    @product = Product.find_by_id(params[:id])
    @features = Feature.all
  end

  def create
    @product = Product.new(params[:product])
    
    respond_to do |format|
      if @product.save
        flash[:notice] = 'Produkt został zapisany.'
        format.html { redirect_to(admin_products_path) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @product = Product.find_by_id(params[:id])
#    params[:product][:category_ids] ||= []    
    respond_to do |format|
      if @product.update_attributes(params[:product])
        flash[:notice] = 'Produkt został zaktualizowany.'
        format.html { redirect_to(admin_products_path) }
        format.js { render :text => '', :status => :ok }
      else
        format.html { render :action => "edit" }
        format.js { render :text => '', :status => :unprocessable_entity }
      end
    end
  end

  def update_pictures
    success = false
    @product = Product.find_by_id(params[:id])
    begin
      @product.pictures.each{|picture| picture.data.reprocess!}    
      success = true
    rescue
    end
    respond_to do |format|
      if success
        format.js { render :text => '', :status => :ok }
      else
        format.js { render :text => '', :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @product = Product.find_by_id(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(admin_products_path) }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :set_current_view_parameters, :only => [:index]
  def index
    if params[:category_id]      	  
      @category = ProductCategory.find_by_permalink(params[:category_id])
      @products = @category ? Product.for_categories(@category.all_children).paginate(:page => params[:page], :per_page => @per_page, :order => @order) : []
	  else
      @products = Product.paginate(:page => params[:page], :per_page => @per_page, :order => @order)
	  end
  end
  
  def show
    @product = Product.find_by_id(params[:id])	  	  
	  render :text => "Nie znaleziono produktu." unless @product
  end   

  def pictures_for_options    
    @product = Product.find_by_id(params[:product_id])
    option_ids = params[:options].reject{|o| o.blank?}.map{|o| o.to_i}.sort
    if option_ids.present?
      photos = @product.option_combinations.select{|oc| option_ids.all?{|optid| oc.options.map(&:id).include?(optid)} }.map{|oc| oc.pictures}.flatten.uniq
    else
      photos = @product.pictures
    end
    render :partial => "photos", :locals => {:photos => photos}
  end

  def change_view
    cookies[:products_index_view] = params[:view] if Product::ALLOWED_VIEWS.keys.include?(params[:view])
    redirect_to :params => params.merge(:action => :index, :view => nil)
  end

  def change_order
    cookies[:products_index_order] = params[:order] if Product::ALLOWED_ORDERS.keys.include?(params[:order])
    redirect_to :params => params.merge(:action => :index, :order => nil)
  end

  protected

  def set_current_view_parameters
    set_current_view
    set_current_order
    @per_page = Product::ALLOWED_VIEWS[@current_view]
    @order = Product::ALLOWED_ORDERS[@current_order]
  end

  def set_current_view
    current_view = cookies[:products_index_view]
    @current_view = current_view.present? && Product::ALLOWED_VIEWS.keys.include?(current_view) ? current_view : 'long_view' 
  end

  def set_current_order
    current_order = cookies[:products_index_order]
    @current_order = current_order.present? && Product::ALLOWED_ORDERS.keys.include?(current_order) ? current_order : 'date' 
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  def setup_option(option)
    returning(option) do |o|
      o.build_texture if o.texture.blank?
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper

  def get_items_view
    @current_view || 'long_view'
  end

  def get_items_order
    @current_order || 'date'
  end
end

app/views/admin/products/_features_form.html.erb
Cecha:
<%= select_tag :feature, options_for_select([['Wybierz',nil]]+@features.map{|p| [p.name, p.id]}), :onchange => remote_function(:update => 'option_combination_form_options', :url => for_feature_admin_options_path, :with => "'feature_id='+this.value + '&product_id=#{product_id}'") %>

app/views/admin/products/_form.html.erb
<% form_for([:admin,  @product], :html => {:multipart => true}) do |f| %>
  <%= f.error_messages %>
  
  <fieldset> <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
    
    <p>
      <label>Nazwa</label>
      <%= f.text_field :name, :class => "text-input small-input" %>
    </p>

<% if false %>
    <p>
      <label>Zdjecie</label>
      <%= image_tag @product.image.url(:thumb) if @product.image %>
      <%= f.file_field :image %>
    </p>
<% end %>

    <p>
      <label>Opis</label>
      <%= f.cktext_area :description, :toolbar=>'Full', :width=>'99%', :language => 'pl' %>
    </p>

    <div class="nested_lists">
      <%= f.label 'product[category_ids][]', "Kategoria" %>

      <% # f.select 'categories', ProductCategory.all.map{|p| [p.name, p.id]} %>
      <% # collection_select :product, :category_ids, ProductCategory.find(:all, :order => 'name ASC'), :id, :name, { :selected => @product.category_ids }, { :multiple => false, :name => 'product[category_ids][]' } -%>

      <%= checkbox_category_list ProductCategory, @product %>
    </div>
        
    <p>
      <label>Status</label>
      <%= f.check_box :status %> Aktywny?
    </p>
                
    <p>
      <input class="button" type="submit" value="Zapisz" />
    </p>
    
  </fieldset>
  
  <div class="clear"></div><!-- End .clear -->
<% end %>

app/views/admin/products/_option_combination_form.html.erb
<% @option_combination ||= OptionCombination.new %>
<% form_remote_for [:admin, @option_combination], :update => "option_combination_form" do |f| %>
  <%= f.hidden_field :product_id, :value => @product.id %>
  <ul id="options_list">
    <% @option_combination.options.each do |option| %>      
      <li>
        <%= hidden_field_tag "option_combination[option_ids][]", option.id %>
        <%= "#{option.feature.name} #{option.name}" %> <%= link_to_function image_tag("icons/cross.png"), "remove_option(this)" %>
      </li>
    <% end %>
  </ul>
  <p>
    Wybierz zdjecia, ktore odnosza sie do wybranej opcji:<br />
  <% @product.pictures.each do |picture| %>
    <%= check_box_tag "option_combination[picture_ids][]", picture.id, @option_combination.pictures.include?(picture) %>
    <%= image_tag picture.url(:thumb) %>
  <% end %>
  </p>
  <%= f.submit 'Zapisz', :name => 'commit' %>
  <% unless @option_combination.new_record? %>    
    <%= link_to_remote 'Usun', :url => admin_option_combination_path(@option_combination), :update => "option_combination_form", :method => :delete %>
  <% end %>
  <%= link_to_remote('Nowa kombinacja', :url => new_admin_option_combination_path(:product_id => @product.id), :update => "option_combination_form", :method => :get) %>
  <br /><%= flash[:notice] %>
<% end %>
<hr />
<h3>Lista kombinacji</h3>
<ul>
  <% @product.option_combinations.each do |option_combination| %>
    <li>          
      <%= link_to_remote option_combination.long_name + ' ' + image_tag("icons/pencil.png"), :url => edit_admin_option_combination_path(option_combination), :update => "option_combination_form", :method => :get %>
      <%= link_to_remote image_tag("icons/cross.png"), :url => admin_option_combination_path(option_combination), :update => "option_combination_form", :method => :delete %>
    </li>
  <% end %>
</ul>
<script type="text/javascript">
  function remove_option(option){
  op = option;
  $(option.parentNode).remove();
  }
</script>

app/views/admin/products/_option_combination_form_options.html.erb
<% form_tag('#') do %>
<%= @options.first.feature.name if @options.present? %>: <%= select_tag "option_combination[option_ids][]", options_for_select(@options.to_a.map{|p| [p.name, "#{p.id}-#{p.long_name}"]}), :id => "new_option" %> <%= button_to_function 'Dodaj', "insert_option(getElementById('new_option').value,getElementById('new_option').innerHtml);return false;" %>
<% end %>
<script type="text/javascript">
function insert_option(option_id,option_name){
var container = $('#options_list');
var option_name = option_id.split("-")[1];
var option_id = option_id.split("-")[0];
var new_option = '<li><input type="hidden" value="' + option_id + '" name="option_combination[option_ids][]"/> ' + option_name + ' <%= link_to_function image_tag("icons/cross.png"), "remove_option(this);"%></li>'; //replace with jquery element
container.append(new_option);
console.log(option_id);
return false;
}
</script>

app/views/admin/products/_product_option_form.html.erb
<% form_for [:admin, ProductOption.new] do |f| %>
  <%= f.hidden_field :product_id, :value => @product.id %>
  <p>
  Opcja: 
  <%= f.select :option_id, @options.to_a.map{|p| [p.name, p.id]} %><br />
  </p>
  <p>
    Wybierz zdjecia, ktore odnosza sie do wybranej opcji:<br />
  <% @product.pictures.each do |picture| %>
    <%= check_box_tag "product_option[picture_ids][]", picture.id, false %>
    <%= image_tag picture.url(:thumb) %>
  <% end %>
  </p>
  <%= f.submit 'Dodaj' %>
<% end %>

app/views/admin/products/edit.html.erb
<div class="content-box">  
  <div class="content-box-header">    
    <h3>Edycja produktu</h3>
    
    <ul class="content-box-tabs">
      <li><a href="#tab1" class="default-tab">Opis</a></li> <!-- href must be unique and match the id of target div -->
      <li><a href="#tab2">Zdjecia</a></li>
      <li><a href="#tab3">Kombinacje atrybutow</a></li>
    </ul>
    
    <div class="clear"></div>
  </div>
  <div class="content-box-content">
    <div class="tab-content default-tab" id="tab1"> <!-- This is the target div. id must match the href of this div's tab -->
      <%= render :partial => "form" %>
      
      <%= link_to 'Wróć', admin_products_path %>
      <%= link_to 'Klonuj', clone_admin_product_path(@product) %>
    </div>
    <div class="tab-content" id="tab2">      
      <% remote_form_for [:admin, @product], :success => "alert('Konfiguracja znakow wodnych aktywna dla nowo uploadowanych zdjec.');", :failure => "alert('Wystapil problem')" do |f| %>
        Znaki wodne: <br />
        Romiq: <%= f.check_box :watermark %><br />
        Archon: <%= f.check_box :watermark_2 %><br />
        <%= f.submit 'Zapisz' %>
      <% end %>
      <%= link_to_remote 'Zastosuj aktualna konfiguracje znakow wodnych do wszystkich zuploadowanych zdjec', :url => update_pictures_admin_product_path(@product), :success => "alert('Zdjecia zaktualizowane')", :failure => "alert('Wystapil problem.')", :loading => "$('#pictures_update_spinner').toggle();", :complete => "$('#pictures_update_spinner').toggle();" %>
      <%= image_tag 'spinner.gif', :style => "display:none;", :id => "pictures_update_spinner" %>
      <ul id="pictures_list">
        <%= render :partial => 'shared/picture', :collection => @product.pictures %>
      </ul>
      <div class="clear"></div>
      
      <%= swfupload_head %>
    
      <%= swfupload :controller => '/admin/pictures', :action => 'create', :assetable_id => @product.id, :assetable_type => @product.class.to_s %>
    
    </div>  
    <div class="tab-content" id="tab3">
      <p>
        Grupa:
      <%= select_tag :group, options_for_select([['Wybierz',nil]]+FeatureCategory.all.map{|p| [p.name, p.id]}), :onchange => remote_function(:update => 'feature_select', :url => for_category_admin_features_path, :with => "'category_id='+this.value + '&product_id=#{@product.id}'") %>
      </p>
      <p id="feature_select">
        <%= render :partial => 'features_form', :locals => {:product_id => @product.id} %>
      </p>
      <div id="option_combination_form_options"></div>
      <div id="option_combination_form">
        <%= render :partial => "option_combination_form" %>
      </div>
    </div>  
  </div>
</div>

<%= sortable_element("pictures_list", :url => { :controller => 'admin/pictures', :action => "order" }, :constraint => false) %>
 

app/views/admin/products/index.html.erb
<div class="content-box"><!-- Start Content Box -->
  
  <div class="content-box-header">
    
    <h3>Zarządzaj produktami</h3>

    <ul class="content-box-tabs">
      <li><a href="#tab1" class="default-tab">Produkty</a></li> <!-- href must be unique and match the id of target div -->
      <li><a href="#tab2">Kategorie</a></li>
      <li><a href="#tab3">Cechy i opcje</a></li>
      <li><a href="#tab4">Grupy cech</a></li>
    </ul>
    
    <div class="clear"></div>
    
  </div> <!-- End .content-box-header -->
  
  <div class="content-box-content">
    
    <div class="tab-content default-tab" id="tab1"> <!-- This is the target div. id must match the href of this div's tab -->
            
      <table>
	
	<thead>
	  <tr>
	    <th>Tytuł</th>
	    <th>Zawartość</th>
	    <th>Status</th>
	    <th style="width:70px;">&nbsp;</th>
	  </tr>
	  
	</thead>
	
	<tfoot>
	  <tr>
	    <td colspan="6">
	      <div class="bulk-actions align-left">
		<%= link_to 'Dodaj produkt', new_admin_product_path %>
	      </div>
	      
	      <div class="pagination" style="display:none;">
		<a href="#" title="First Page">&laquo; First</a><a href="#" title="Previous Page">&laquo; Previous</a>
		<a href="#" class="number" title="1">1</a>
		<a href="#" class="number" title="2">2</a>
		<a href="#" class="number current" title="3">3</a>
		<a href="#" class="number" title="4">4</a>
		<a href="#" title="Next Page">Next &raquo;</a><a href="#" title="Last Page">Last &raquo;</a>
	      </div> <!-- End .pagination -->
	      <div class="clear"></div>
	    </td>
	  </tr>
	</tfoot>
	
	<tbody>

	  <% @products.each do |product| %>
	  <tr class="parent">
	    <td class="name"><%= link_to product.name, edit_admin_product_path(product) %></td>
	    <td><%= truncate(strip_tags(product.description), :length => 100) %></td>
	    <td><%=h product.status.to_s(:activation) %></td>
	    <td>
	      <%= link_to '<img src="/images/icons/pencil.png" alt="Edytuj" />', edit_admin_product_path(product) %>
	      <%= link_to '<img src="/images/icons/cross.png" alt="Usuń" />', [:admin, product], :confirm => 'Jesteś pewien?', :method => :delete %>
	    </td>
	  </tr>
	  <% end %>
	</tbody>
	
      </table>
      
    </div> <!-- End #tab1 -->

    <div class="tab-content" id="tab2"> <!-- This is the target div. id must match the href of this div's tab -->
      <h3>Kategorie</h3>
      <%= category_list ProductCategory, true %>
    </div>

    <div class="tab-content" id="tab3"> <!-- This is the target div. id must match the href of this div's tab -->
      <h3>Cechy i opcje</h3>
      <ul>
      <% FeatureCategory.all.each do |group| %> 
        <li>
          <%= group.name %>
          <ul>
            <% group.items.each do |feature| %>
              <% @features -= [feature] %>
              <li>
                <%= link_to feature.name, edit_admin_feature_path(feature) %>
                <%= link_to image_tag("icons/plus.png"), new_admin_option_path(:feature_id => feature.id), :title => "Dodaj nowa ceche" %>
                <% if feature.options.present? %>
                  <ul>
                    <% feature.options.each do |option| %>
                      <li><%= link_to option.name + ' ' + image_tag("icons/pencil.png"), edit_admin_option_path(option) %></li>
                    <% end %>
                  </ul>
                <% end %>
              </li>
            <% end %>        
          </ul>
        </li>
      <% end %>
      </ul>
      <ul>
        <% @features.each do |feature| %>
          <li>
            <%= link_to feature.name, edit_admin_feature_path(feature) %>
            <%= link_to image_tag("icons/plus.png"), new_admin_option_path(:feature_id => feature.id), :title => "Dodaj nowa ceche" %>
            <% if feature.options.present? %>
              <ul>
                <% feature.options.each do |option| %>
                  <li><%= link_to option.name + ' ' + image_tag("icons/pencil.png"), edit_admin_option_path(option) %></li>
                <% end %>
              </ul>
            <% end %>
          </li>
        <% end %>        
      </ul>
      <%= link_to 'Dodaj nowa ceche', new_admin_feature_path %>
    </div>

    <div class="tab-content" id="tab4"> <!-- This is the target div. id must match the href of this div's tab -->
      <h3>Kategorie</h3>
      <%= category_list FeatureCategory, true %>
    </div>

  </div> <!-- End .content-box-content -->
  
</div> <!-- End .content-box -->

app/views/admin/products/new.html.erb
<div class="content-box">  
  <div class="content-box-header">    
    <h3>Nowy product</h3>
  </div>
  <div class="content-box-content">
    <%= render :partial => "form" %>
    
    <%= link_to 'Wróć', admin_products_path %>
  </div>  
</div>

app/views/admin/products/show.html.erb
<p>
  <b>Name:</b>
  <%=h @product.name %>
</p>

<p>
  <b>Body:</b>
  <%=h @product.body %>
</p>

<p>
  <b>Status:</b>
  <%=h @product.status %>
</p>

<%= link_to 'Edit', edit_admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>